name: app
description: App for comparing weather from different locations. Based on data received from OpenWeather API.
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  copy_with_extension: ^4.0.2
  dio: ^4.0.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^1.0.0
  hive: ^2.1.0
  intl: ^0.17.0
  json_annotation: ^4.3.0
  path_provider: ^2.0.8
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.1.4
  copy_with_extension_gen: ^4.0.2
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.2
  json_serializable: ^6.0.1
  lint: ^1.7.2

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
  
fonts:
  - family: Roboto
    fonts:
      - asset: fonts/Roboto-Light.ttf
        weight: 300
      - asset: fonts/Roboto-Regular.ttf
        weight: 400
      - asset: fonts/Roboto-Medium.ttf
        weight: 500
      - asset: fonts/Roboto-Bold.ttf
        weight: 700